version: '3'

services:
  frontend:
    container_name: ipv6db_frontend
    build: frontend/
    image: ipv6db:latest
    depends_on:
      - backend
    links:
      - backend

  backend:
    container_name: ipv6db_backend
    image: redis:latest
