services:
  frontend:
    container_name: ipv6db_frontend
    image: cloudyfunctor/ipv6db:0.3.3.2
    depends_on:
      - backend
    links:
      - backend

  backend:
    container_name: ipv6db_backend
    image: redis:latest
